//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DatabaseEntities4 : DbContext
{
    public DatabaseEntities4()
        : base("name=DatabaseEntities4")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<APARTMENT> APARTMENTs { get; set; }
    public virtual DbSet<CAR> CARS { get; set; }
    public virtual DbSet<OFFER> OFFERS { get; set; }
    public virtual DbSet<USER> USERs { get; set; }
}
