//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class APARTMENT
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public APARTMENT()
    {
        this.OFFERS = new HashSet<OFFER>();
    }

    public int POSTAL_CODE { get; set; }
    public string CITY { get; set; }
    public int NUM_ROOM { get; set; }
    public string DETAILS { get; set; }
    public string PIC { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OFFER> OFFERS { get; set; }
}

public partial class CAR
{
    public string FDATE;

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CAR()
    {
        this.OFFERS = new HashSet<OFFER>();
    }

    public int ID { get; set; }
    public string TYPE { get; set; }
    public string COLOR { get; set; }
    public int YEAR { get; set; }
    public string DETAILS { get; set; }
    public string HAND { get; set; }
    public string CITY { get; set; }
    public string PIC { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OFFER> OFFERS { get; set; }
    public int PRICE { get; internal set; }
    public string BEGINPRICE { get; set; }
}

public partial class OFFER
{
    public int Id { get; set; }
    public int PROId { get; set; }
    public int PERSONID { get; set; }
    public int PRICE { get; set; }

    public virtual APARTMENT APARTMENT { get; set; }
    public virtual CAR CAR { get; set; }
    public virtual USER USER { get; set; }
}

public partial class USER
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public USER()
    {
        this.OFFERS = new HashSet<OFFER>();
    }

    public int Id { get; set; }
    public System.DateTime BDATE { get; set; }
    public string PHONE { get; set; }
    public string EMAIL { get; set; }
    public string CITY { get; set; }
    public string CREAIT_CARD { get; set; }
    public string CVV { get; set; }
    public string CDATE { get; set; }
    public int TYPE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<OFFER> OFFERS { get; set; }
}
